Add autocomplete files to archives
The autocomplete files are missing from the released archives. This causes a failure in the brew install/updates:

Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - todoist_functions.sh

Although todoist_functions_fzf_bash.sh is not needed, added for completeness for those using Bash.